Repository cloudfour/cloudfour.com-patterns, pull requests merged in 2020-03, with the labels that each got.

#509 Add pull request template
  .github/pull_request_template.md
Labels: 👷 environment, 📚 documentation

#435 Add Safari 10 to browserslist
  browserslist
Labels: 🗿 legacy

#508 Templatize SVG assets
  .svgo.yml
  gulpfile.js
  package-lock.json
  package.json
  src/assets/.gitignore
  src/objects/icon/examples/basic.twig
  src/objects/icon/examples/inline.twig
  src/objects/icon/icon.stories.mdx
  src/objects/icon/icon.twig
Labels: 👷 environment

#513 Improve README
  README.md
Labels: 📚 documentation

#512 Add choosable backgrounds
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
Labels: 👷 environment

#511 Add basic motion design tokens
  src/demo/button/button.scss
  src/design-tokens/_easing.yml
  src/design-tokens/_speed.yml
  src/design-tokens/colors.stories.mdx
  src/design-tokens/colors.yml
  src/design-tokens/motion.stories.mdx
  src/design-tokens/motion.yml
Labels: 🎨 design, 📚 documentation

#507 Install CSS linting
  .stylelintrc.json
  package-lock.json
  package.json
  src/base/_defaults.scss
  src/base/_typography.scss
  src/mixins/_unit.scss
  src/objects/icon/icon.scss
Labels: ✍️ help wanted, 👷 environment

#516 Basic size and scale tokens
  src/demo/button/button.scss
  src/design-tokens/modular-scale.yml
  src/design-tokens/sizes.stories.mdx
  src/design-tokens/sizes.yml
  src/mixins/_ms.scss
Labels: 🎨 design, 📚 documentation

#520 Separate gulp tasks
  README.md
  gulpfile.js/index.js
  gulpfile.js/tasks/svg-to-twig.js
  package-lock.json
  package.json
Labels: 👷 environment

#519 Basic Button pattern
  .storybook/preview.js
  package-lock.json
  package.json
  src/demo/button/button.scss
  src/demo/button/button.stories.mdx
  src/demo/heading/heading.stories.js
  src/design-tokens/sizes.yml
  src/mixins/_focus.scss
  src/mixins/_unit.scss
  src/objects/button/button.scss
  src/objects/button/button.stories.mdx
  src/objects/button/button.twig
  src/objects/button/demo/elements.twig
  src/objects/button/demo/styles.twig
  src/objects/icon/demo/basic.twig
  src/objects/icon/demo/inline.twig
  src/objects/icon/icon.stories.mdx
Labels: 🎨 design, 📚 documentation

#522 Set some default colors in base styles
  .storybook/preview.scss
  src/base/_defaults.scss
  src/design-tokens/colors.yml
Labels: 🎨 design

#524 Dark theme + dark-optimized buttons
  src/objects/button/button.scss
  src/objects/button/button.stories.mdx
  src/objects/button/demo/styles-dark.twig
  src/objects/button/demo/styles.twig
  src/themes/_dark.scss
  src/themes/_index.scss
  src/themes/demo/fill-canvas.twig
  src/themes/themes.stories.mdx
Labels: 🎨 design

#531 Replace backgrounds add-on with themes
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/objects/button/button.stories.mdx
  src/themes/demo/fill-canvas.twig
  src/themes/themes.stories.mdx
Labels: 👷 environment, 🔌 dependencies

#543 Font tokens and WIP typographic specimens
  src/base/_typography.scss
  src/design-tokens/_font-family.yml
  src/design-tokens/_font-weight.yml
  src/design-tokens/font.yml
  src/design/typography/demo/blockquote.twig
  src/design/typography/demo/code-block.twig
  src/design/typography/demo/headings.twig
  src/design/typography/demo/list-description.twig
  src/design/typography/demo/list-ordered.twig
  src/design/typography/demo/list-unordered.twig
  src/design/typography/demo/paragraphs.twig
  src/design/typography/typography.stories.mdx
  src/objects/button/button.scss
Labels: 🎨 design, 📚 documentation

#544 Fluid responsive type lock
  src/base/_typography.scss
  src/mixins/_fluid.scss
Labels: 🎨 design

#545 More typographic patterns
  package-lock.json
  package.json
  src/base/_defaults.scss
  src/base/_typography.scss
  src/design-tokens/opacity.yml
  src/design/typography/demo/inline-elements.twig
  src/design/typography/typography.stories.mdx
  src/mixins/_headings.scss
  src/themes/_dark.scss
  src/vendor/prism/_theme.scss
  src/vendor/prism/config.js
Labels: 🎨 design, 📚 documentation

#573 Replace centered add-on with paddings
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/button/button.stories.mdx
  src/themes/demo/fill-canvas.twig
  src/themes/themes.stories.mdx
Labels: 👷 environment
